# btc.stateful.set.yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin
spec:
  serviceName: bitcoin
  replicas: 1 # Scale as match as you want
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bitcoin
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
      restartPolicy: Always
      containers:
        - name: bitcoin
          image: moabukar/btc:v1
          volumeMounts:
            - name: bitcoin
              mountPath: /root/.bitcoin
  volumeClaimTemplates:
    - metadata:
        name: bitcoin
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: bitcoin-disk
        resources:
          requests:
            storage: 500Gi
